# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Check Macos version
        run: sw_vers -productVersion
      - uses: actions/checkout@v2
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_12.4.app/Contents/Developer
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild -sdk iphonesimulator -configuration Debug build 
